# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/py-chronicle',
                'doc_host': 'https://andrie.github.io',
                'git_url': 'https://github.com/andrie/py-chronicle',
                'lib_path': 'chronicle'},
  'syms': { 'chronicle.core': { 'chronicle.core.ChronicleLogs': ('core.html#chroniclelogs', 'chronicle/core.py'),
                                'chronicle.core.ChronicleLogs.__init__': ('core.html#chroniclelogs.__init__', 'chronicle/core.py'),
                                'chronicle.core.ChronicleLogs.filter_type': ('core.html#chroniclelogs.filter_type', 'chronicle/core.py'),
                                'chronicle.core.ChronicleMetrics': ('core.html#chroniclemetrics', 'chronicle/core.py'),
                                'chronicle.core.ChronicleMetrics.__init__': ('core.html#chroniclemetrics.__init__', 'chronicle/core.py'),
                                'chronicle.core.ChronicleMetrics.describe': ('core.html#chroniclemetrics.describe', 'chronicle/core.py'),
                                'chronicle.core.ChronicleMetrics.filter': ('core.html#chroniclemetrics.filter', 'chronicle/core.py'),
                                'chronicle.core.ChronicleMetrics.plot': ('core.html#chroniclemetrics.plot', 'chronicle/core.py'),
                                'chronicle.core.read_chronicle': ('core.html#read_chronicle', 'chronicle/core.py')}}}
