# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/read.ipynb.

# %% auto 0
__all__ = ['read_chronicle', 'read_chronicle_metrics', 'read_chronicle_logs']

# %% ../nbs/read.ipynb 4
import polars as pl
import pyarrow.parquet as pq
# import pyarrow.dataset as ds
# from s3fs import S3FileSystem
# import pandas as pd
# from fastcore.basics import patch
# import re

# %% ../nbs/read.ipynb 6
def read_chronicle(
        path: str, # Path to dataset,
        type: str = "", # must be `metrics` or `logs`
        date:str = "", # date in format `YYYY/MM/DD` 
        version: str = "v1" # currently must be `v1`
    ) -> pl.DataFrame:
    "Read a chronicle parquet file into a polars dataframe."
    path = f"{path}/{version}/{type}/{date}"
    return pl.from_arrow(pq.read_table(path))



# %% ../nbs/read.ipynb 7
def read_chronicle_metrics(
        path: str, # Path to dataset,
        date:str = "", # date in format `YYYY/MM/DD` 
        version: str = "v1" # currently must be `v1`
) -> pl.DataFrame:
    "Read a chronicle metrics parquet file into a polars dataframe."
    return read_chronicle(path, "metrics", date, version = version) 

def read_chronicle_logs(
        path: str, # Path to dataset,
        date:str = "", # date in format `YYYY/MM/DD` 
        version: str = "v1" # currently must be `v1`
) -> pl.DataFrame:
    "Read a chronicle logs parquet file into a polars dataframe."
    return read_chronicle(path, "logs", date, version) 

