# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/py-chronicle',
                'doc_host': 'https://andrie.github.io',
                'git_url': 'https://github.com/andrie/py-chronicle',
                'lib_path': 'py_chronicle'},
  'syms': { 'py_chronicle.core': { 'py_chronicle.core.describe_measures': ('core.html#describe_measures', 'py_chronicle/core.py'),
                                   'py_chronicle.core.get_metric_values': ('core.html#get_metric_values', 'py_chronicle/core.py'),
                                   'py_chronicle.core.plot_metric_values': ('core.html#plot_metric_values', 'py_chronicle/core.py'),
                                   'py_chronicle.core.read_chronicle': ('core.html#read_chronicle', 'py_chronicle/core.py')}}}
