# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['read_chronicle', 'ChronicleMetrics', 'ChronicleLogs']

# %% ../nbs/00_core.ipynb 3
import polars as pl
import pyarrow.parquet as pq
import pyarrow.dataset as ds
from s3fs import S3FileSystem
import pandas as pd
import plotly.express as px
from fastcore.basics import patch

# %% ../nbs/00_core.ipynb 5
def read_chronicle(
        dataset: str # Path to dataset
    ) -> pl.DataFrame:
    "Read a chronicle parquet file into a polars dataframe."
    df = pl.from_arrow(pq.read_table(dataset))
    return df


# %% ../nbs/00_core.ipynb 10
@pl.api.register_dataframe_namespace("metrics")
class ChronicleMetrics:
    def __init__(self, df: pl.DataFrame):
        self._df = df

    def describe(self) -> pl.DataFrame:
        "Reads metrics dataframe and returns a pandas dataframe with summary of service, name and description of all metrics"
        return (
            self._df
            .groupby("service", "name")
            .agg(
                pl.col("description").unique(),
                pl.col("value_column").unique(),
            )
            .sort("service", "name")
            .to_pandas()
        )


# %% ../nbs/00_core.ipynb 13
@patch
def filter(self: ChronicleMetrics, 
        name:str, # name of metric to extract
        alias:str # alias to use for new column
    ) -> pd.DataFrame:
    "Extract a single metric from a metrics dataframe"
    return (
        self._df
        .lazy()
        .filter(pl.col("name") == name)
        .sort(pl.col("host"), pl.col("timestamp"))
        .select([
            "host",
            pl.col("timestamp"),
            pl.col("value_float").alias(alias)
        ])
        .collect()
        .to_pandas()
    )


# %% ../nbs/00_core.ipynb 16
@patch
def plot(
        self:ChronicleMetrics, # metrics dataframe
        name:str, # name of metric to extract
        alias:str # alias to use for new column
    ) -> px.line: 
    "Plot a selected metric using a Plotly line plot"

    dat = self._df.metrics.filter(name, alias) 
    fig = px.line(dat, x='timestamp', y=alias, line_group="host", color="host")
    return fig



# %% ../nbs/00_core.ipynb 19
@pl.api.register_dataframe_namespace("logs")
class ChronicleLogs:
    def __init__(self, df: pl.DataFrame):
        self._df = df

# %% ../nbs/00_core.ipynb 20
@patch
def filter_type(self: ChronicleLogs,
                value: str # Value to extract 
    ) -> pd.DataFrame:
    "Extract all logs where type == value"
    return (
        self._df
        .lazy()
        .with_columns([
            (pl.col("body").str.json_path_match(f"$.{value}").alias(f".{value}")),
            (pl.col("body").str.json_path_match("$.type").alias(".type"))
        ])
        .filter(pl.col(f".{value}").is_not_null())
        .select(["service", "host", "timestamp", f".{value}", ".type", "body"])
        .sort("service", "host", f".{value}", "timestamp")
        .collect()
    )
