# Some comment

default:
  workbench:
    ram: 
      name:    memory_percent
      service: workbench-health
      title:   Worbench memory used (percentage)
      alias: 
    cpu:
      name:    cpu_percent
      service: workbench-health
      title:   Workbench CPU used (percentage)
      alias:
    cpu_user:
      name:    rstudio_system_cpu_usage_user
      service: workbench-metrics
      title:   Graphite metric rstudio_system_cpu_usage_user 
  connect:
    ram: 
      name:    rsconnect_system_memory_used
      service: connect-metrics
      title:   Connect system memory used
      alias: 
    cpu:
      name:    rsconnect_system_cpu_user
      service: connect-metrics
      title:   Connect system CPU used
      alias:
    cpu_user:
      name:    rsconnect_cpu_user
      service: connect-metrics
      title:   Graphite metric rsconnect_cpu_user
    license_users:
      name:    rsconnect_license_active365day
      service: connect-metrics
      title:   Graphite metric rsconnect_license_active365day
