# Some comment

default:
  workbench:
    ram: 
      name:    memory_percent
      service: workbench-health
      title:   Worbench memory used (percentage)
      alias: 
    cpu:
      name:    cpu_percent
      service: workbench-health
      title:   Workbench CPU used (percentage)
      alias: 
  connect:
    ram: 
      name:    rsconnect_system_memory_used
      service: connect-metrics
      title:   Connect system memory used
      alias: 
    cpu:
      name:    rsconnect_system_cpu_user
      service: connect-metrics
      title:   Connect system CPU used
      alias: 
